language: node_js
node_js:
  - "lts/*"
cache: yarn
env:
  - PGUSER=postgres PGHOST=localhost PGPASSWORD=admin PGDATABASE=mydb PGPORT=5432
services:
  - postgresql
before-script:
  - psql -c "create database sendit" -U postgres
  - psql -f sql/createdb.sql -U postgres
  - psql -f sql/create_admin.sql -U postgres