language: node_js
node_js:
  - "lts/*"
cache: yarn
env:
  global:
    - PGUSER=postgres PGHOST=localhost PGPASSWORD=admin PGDATABASE=sendit PGPORT=5432
services:
  - postgresql
postgres:
  adapter: postgresql
  database: sendit
  username: postgres
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before-script:
  - psql -c "create database sendit;" -U postgres
  - psql -f sql/createdb.sql -U postgres
  - psql -f sql/create_admin.sql -U postgres
script: "npm run-script test"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"