dist: trusty
language: node_js
node_js:
  - "lts/*"
cache: yarn
env:
  - DB=sendit
services:
  - postgresql
postgres:
  adapter: postgresql
  database: sendit
  username: postgres
before-script:
  - psql -c "CREATE DATABASE sendit;" -U postgres
  - psql -d sendit -f sql/createdb.sql -U postgres
  - psql -d sendit -f sql/create_admin.sql -U postgres
script: npm run test
# Send coverage data to Coveralls
# after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
after_script: npm run coverage
